Resources:
    MyFirstInstance:
        Type: AWS::EC2::Instance
        Properties:
            AvailabilityZone: us-east-1a
            ImageId: ami-01df81788f1c7d639
            InstanceType: t2.micro
